// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAh7daQ28Dj_gRqOBruppbcZWoVzEr2Ig',
    appId: '1:987699128479:web:e719e48affe0f3ee14daaa',
    messagingSenderId: '987699128479',
    projectId: 'attendance-tracker-46-6d0e7',
    authDomain: 'attendance-tracker-46-6d0e7.firebaseapp.com',
    storageBucket: 'attendance-tracker-46-6d0e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH0Hn4HShBiWFL_TtVEjXDiMMW9hAQgLI',
    appId: '1:987699128479:android:582ca6455142454514daaa',
    messagingSenderId: '987699128479',
    projectId: 'attendance-tracker-46-6d0e7',
    storageBucket: 'attendance-tracker-46-6d0e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAN86op15fXCuqUccB6sjVLeclyU5zAE',
    appId: '1:987699128479:ios:8a0246e68afb8cde14daaa',
    messagingSenderId: '987699128479',
    projectId: 'attendance-tracker-46-6d0e7',
    storageBucket: 'attendance-tracker-46-6d0e7.appspot.com',
    iosBundleId: 'com.example.attendanceTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRAN86op15fXCuqUccB6sjVLeclyU5zAE',
    appId: '1:987699128479:ios:8a0246e68afb8cde14daaa',
    messagingSenderId: '987699128479',
    projectId: 'attendance-tracker-46-6d0e7',
    storageBucket: 'attendance-tracker-46-6d0e7.appspot.com',
    iosBundleId: 'com.example.attendanceTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAh7daQ28Dj_gRqOBruppbcZWoVzEr2Ig',
    appId: '1:987699128479:web:57054489e25810f714daaa',
    messagingSenderId: '987699128479',
    projectId: 'attendance-tracker-46-6d0e7',
    authDomain: 'attendance-tracker-46-6d0e7.firebaseapp.com',
    storageBucket: 'attendance-tracker-46-6d0e7.appspot.com',
  );
}
